# Generated by Django 3.2.5 on 2021-09-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=15)),
                ('json_file', models.JSONField(default=list)),
                ('region', models.CharField(choices=[('NA1', 'AMERICAS'), ('BR1', 'AMERICAS'), ('LA1', 'AMERICAS'), ('LA2', 'AMERICAS'), ('OC1', 'AMERICAS'), ('EUN1', 'EUROPE'), ('EUW1', 'EUROPE'), ('TR1', 'EUROPE'), ('RU', 'EUROPE'), ('KR', 'ASIA'), ('JP1', 'ASIA')], max_length=4)),
            ],
        ),
    ]
