# Generated by Django 4.0.1 on 2022-12-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=15)),
                ('match_json', models.JSONField(default=dict)),
                ('summoner', models.CharField(max_length=50)),
                ('summoner_json', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-match_id'],
            },
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner', models.CharField(max_length=50)),
                ('matches', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('champions', models.JSONField(default=dict)),
                ('roles', models.JSONField(default=dict)),
                ('stats', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-matches'],
            },
        ),
    ]
