# Generated by Django 3.2.5 on 2021-09-25 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.CharField(max_length=15)),
                ('summary_json', models.JSONField(default=dict)),
                ('summoner', models.CharField(max_length=50)),
            ],
        ),
    ]
