# Generated by Django 4.0.1 on 2022-06-14 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_match_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner', models.CharField(max_length=50)),
                ('champions', models.JSONField(default=dict)),
                ('friends', models.JSONField(default=dict)),
                ('roles', models.JSONField(default=dict)),
                ('stats', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
