# Generated by Django 4.0.1 on 2022-06-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_summoner'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='games',
            field=models.IntegerField(default=0),
        ),
    ]
