# Generated by Django 4.0.1 on 2022-06-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_summoner_games'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summoner',
            name='friends',
        ),
    ]
