# Generated by Django 4.0.1 on 2022-06-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_summoner_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='summoner',
            name='minutes',
            field=models.IntegerField(default=0),
        ),
    ]
