# Generated by Django 4.0.1 on 2022-07-01 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_summoner_minutes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-match_id']},
        ),
        migrations.AlterModelOptions(
            name='summoner',
            options={'ordering': ['-games']},
        ),
    ]
