# Generated by Django 4.0.1 on 2022-07-05 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_match_options_alter_summoner_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='summoner',
            options={'ordering': ['-matches']},
        ),
        migrations.RenameField(
            model_name='summoner',
            old_name='games',
            new_name='matches',
        ),
    ]
