# Generated by Django 4.0.1 on 2022-07-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_summoner_options_rename_games_summoner_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player_json',
            field=models.JSONField(default=dict),
        ),
    ]
